services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./EasyRent_Dump.sql:/docker-entrypoint-initdb.d/EasyRent_Dump.sql


volumes:
  postgres_data: